#!/bin/bash
#
# switch-to-hdr.sh — Switch Sunshine to gamescope/HDR capture mode
#
# Reconfigures Sunshine to use wlr-screencopy against gamescope's Wayland
# display (gamescope-0), then restarts Sunshine and waits for it to be
# ready. Run this from the COSMIC desktop BEFORE connecting from Moonlight.
#
# This is the correct entry point for HDR streaming. Reconfiguring Sunshine
# while a Moonlight client is already connected causes a 503 error because
# the Sunshine restart window outlasts Moonlight's reconnect timeout. By
# running this script first, Sunshine is fully up with the correct capture
# backend before the client ever connects.
#
# Usage:
#   ./switch-to-hdr.sh          — switch to HDR mode (wlr capture)
#   ./switch-to-hdr.sh --restore — switch back to SDR mode (kms capture)
#
# The companion scripts sunshine-start-gamescope.sh / sunshine-stop-gamescope.sh
# handle gamescope itself and MUST be configured as Sunshine prep-cmds in
# apps.json. This script only handles the Sunshine configuration switch.
#

set -euo pipefail

SUNSHINE_CONF="${XDG_CONFIG_HOME:-$HOME/.config}/sunshine/sunshine.conf"
# Backup stored beside the config so it survives reboots (crash recovery)
SUNSHINE_CONF_BACKUP="${XDG_CONFIG_HOME:-$HOME/.config}/sunshine/sunshine.conf.gamescope-backup"
# Drop-in in runtime dir so it is auto-cleaned on reboot/logout
SUNSHINE_DROPIN_DIR="${XDG_RUNTIME_DIR}/systemd/user/sunshine.service.d"
SUNSHINE_DROPIN="${SUNSHINE_DROPIN_DIR}/gamescope-wlr.conf"

RESTORE=false
if [ "${1:-}" = "--restore" ]; then
    RESTORE=true
fi

log() { echo "[switch-to-hdr] $*"; }

# XDG_RUNTIME_DIR is required for the systemd drop-in path.
# It is set by the login session (PAM/systemd); if missing, bail early
# rather than silently falling back to /tmp where systemd won't find the drop-in.
if [ -z "${XDG_RUNTIME_DIR:-}" ]; then
    log "ERROR: XDG_RUNTIME_DIR is not set — cannot install systemd drop-in"
    log "       Run this script from an interactive login session, not a bare shell"
    exit 1
fi

# ── Wait for Sunshine to be accepting connections ─────────────────
# Polls the Sunshine HTTPS API (port 47990) until it responds or times out.
wait_for_sunshine() {
    local timeout="${1:-30}"
    local elapsed=0
    log "Waiting for Sunshine to be ready (timeout ${timeout}s)..."
    while [ "$elapsed" -lt "$timeout" ]; do
        if curl -sk --max-time 2 "https://localhost:47990" > /dev/null 2>&1; then
            log "Sunshine is ready"
            return 0
        fi
        sleep 1
        elapsed=$((elapsed + 1))
    done
    log "WARNING: Sunshine did not respond within ${timeout}s — it may still be starting up"
    return 1
}

# ── Switch to HDR mode (wlr capture) ─────────────────────────────
switch_to_hdr() {
    log "Switching Sunshine to HDR/gamescope mode (capture = wlr)..."

    # Idempotency: if sunshine.conf already has capture = wlr, we are already
    # in HDR mode. Running switch_to_hdr() a second time would overwrite the
    # backup with the already-swapped config — do nothing instead.
    if [ -f "$SUNSHINE_CONF" ] && grep -q '^capture[[:space:]]*=[[:space:]]*wlr' "$SUNSHINE_CONF"; then
        log "Already in HDR mode (capture = wlr) — nothing to do"
        exit 0
    fi

    # Remove any stale backup from a previous crashed session
    if [ -f "$SUNSHINE_CONF_BACKUP" ]; then
        log "WARNING: Stale backup found — removing before creating fresh backup"
        rm -f "$SUNSHINE_CONF_BACKUP"
    fi

    # Back up current sunshine.conf
    if [ -f "$SUNSHINE_CONF" ]; then
        cp "$SUNSHINE_CONF" "$SUNSHINE_CONF_BACKUP"
        log "Backed up sunshine.conf → sunshine.conf.gamescope-backup"
    fi

    # Rewrite sunshine.conf: replace capture line with wlr
    {
        if [ -f "$SUNSHINE_CONF_BACKUP" ]; then
            grep -v '^capture[[:space:]]*=' "$SUNSHINE_CONF_BACKUP" || true
        fi
        echo "capture = wlr"
    } > "$SUNSHINE_CONF"
    log "sunshine.conf: capture = wlr"

    # Write systemd drop-in to inject WAYLAND_DISPLAY=gamescope-0
    mkdir -p "$SUNSHINE_DROPIN_DIR"
    cat > "$SUNSHINE_DROPIN" <<EOF
# Generated by switch-to-hdr.sh — removed by switch-to-hdr.sh --restore
[Service]
Environment=WAYLAND_DISPLAY=gamescope-0
EOF
    log "Wrote systemd drop-in: $SUNSHINE_DROPIN"

    # Reload and restart Sunshine synchronously
    # Safe here because this script is NOT running inside Sunshine's process tree
    log "Restarting Sunshine with new configuration..."
    systemctl --user daemon-reload
    systemctl --user restart sunshine

    # Wait for Sunshine to be accepting connections
    wait_for_sunshine 60 || true

    echo
    log "Done. Sunshine is running with capture=wlr and WAYLAND_DISPLAY=gamescope-0"
    log "Now connect from Moonlight and launch 'Steam Big Picture (Gamescope HDR)'"
    log "Gamescope will start and take over the display for HDR streaming"
}

# ── Restore to SDR mode (kms capture) ────────────────────────────
switch_to_sdr() {
    log "Restoring Sunshine to SDR/COSMIC mode (capture = kms)..."

    # Restore original sunshine.conf from backup
    if [ -f "$SUNSHINE_CONF_BACKUP" ]; then
        cp "$SUNSHINE_CONF_BACKUP" "$SUNSHINE_CONF"
        rm -f "$SUNSHINE_CONF_BACKUP"
        log "Restored sunshine.conf from backup"
    else
        log "WARNING: No backup found — patching capture = kms directly"
        if [ -f "$SUNSHINE_CONF" ]; then
            {
                grep -v '^capture[[:space:]]*=' "$SUNSHINE_CONF" || true
                echo "capture = kms"
            } > "${SUNSHINE_CONF}.tmp" && mv "${SUNSHINE_CONF}.tmp" "$SUNSHINE_CONF"
        else
            echo "capture = kms" > "$SUNSHINE_CONF"
        fi
    fi
    log "sunshine.conf: capture = kms"

    # Remove systemd drop-in
    if [ -f "$SUNSHINE_DROPIN" ]; then
        rm -f "$SUNSHINE_DROPIN"
        rmdir "$SUNSHINE_DROPIN_DIR" 2>/dev/null || true
        log "Removed systemd drop-in"
    fi

    # Reload and restart Sunshine synchronously
    log "Restarting Sunshine with restored configuration..."
    systemctl --user daemon-reload
    systemctl --user restart sunshine

    wait_for_sunshine 60 || true

    echo
    log "Done. Sunshine is running with capture=kms (COSMIC desktop streaming)"
}

# ── Main ──────────────────────────────────────────────────────────
if $RESTORE; then
    switch_to_sdr
else
    switch_to_hdr
fi
